/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author VIP5-SEPT-17
 */
public class AccueilN  extends javax.swing.JFrame {

    /**
     * Creates new form Acceil
     */
    public AccueilN () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        empL = new javax.swing.JButton();
        empP = new javax.swing.JButton();
        delai = new javax.swing.JButton();
        rest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        empL.setText("Empreinter Livre");
        empL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empLActionPerformed(evt);
            }
        });

        empP.setText("Empreinter Périodique");
        empP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empPActionPerformed(evt);
            }
        });

        delai.setText("Vérifier délai");
        delai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delaiActionPerformed(evt);
            }
        });

        rest.setText("Restituer");
        rest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(empL)
                    .addComponent(empP)
                    .addComponent(delai)
                    .addComponent(rest))
                .addContainerGap(253, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(empL)
                .addGap(18, 18, 18)
                .addComponent(empP)
                .addGap(18, 18, 18)
                .addComponent(delai)
                .addGap(18, 18, 18)
                .addComponent(rest)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void empLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empLActionPerformed
        this.setVisible(false);
        Rechercher rl= new Rechercher();
        rl.setVisible(true);
    }//GEN-LAST:event_empLActionPerformed

    private void empPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empPActionPerformed
        this.setVisible(false);
        RechercherP rp= new RechercherP();
        rp.setVisible(true);
    }//GEN-LAST:event_empPActionPerformed

    private void delaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delaiActionPerformed
        this.setVisible(false);
        deadline d= new deadline();
        d.setVisible(true);
     }//GEN-LAST:event_delaiActionPerformed

    private void restActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restActionPerformed
        this.setVisible(false);
        restituer r= new restituer();
        r.setVisible(true);
    }//GEN-LAST:event_restActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccueilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccueilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccueilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccueilN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccueilN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delai;
    private javax.swing.JButton empL;
    private javax.swing.JButton empP;
    private javax.swing.JButton rest;
    // End of variables declaration//GEN-END:variables
}
